import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://sandbox.gk.mvsi.com/');
    await page.getByRole('textbox', { name: 'Email Address' }).click();
    await page.getByRole('textbox', { name: 'Email Address' }).fill('yuz@mvsi.com');
    await page.getByRole('textbox', { name: 'Email Address' }).press('Tab');
    await page.getByRole('textbox', { name: 'Password' }).fill('Test.1234');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByRole('button', { name: 'Orders' }).click();
    await page.locator('button').nth(2).click();
    await page.getByRole('textbox').first().fill('Test');
    await page.getByRole('textbox').first().press('Tab');
    await page.locator('input[type="email"]').fill('test@test.com');
    await page.locator('input[type="email"]').press('Tab');
    await page.getByRole('textbox').nth(2).fill('1');
    await page.getByRole('textbox').nth(2).press('Tab');
    await page.getByRole('textbox').nth(3).fill('1');
    await page.getByRole('textbox').nth(3).press('Tab');
    await page.getByRole('textbox').nth(4).fill('qa');
    await page.getByRole('textbox').nth(4).press('Tab');
    await page.locator('form').getByRole('button').filter({ hasText: /^$/ }).press('Enter');
    await page.getByRole('textbox', { name: 'Select Company *' }).click();
    await page.getByRole('textbox', { name: 'Select Company *' }).fill('Lati');
    await page.getByRole('button', { name: 'Latitude Finance' }).click();
    await page.getByRole('textbox', { name: 'Select Client *' }).click();
    await page.getByRole('button', { name: 'Yu Zhang', exact: true }).click();
    await page.getByRole('textbox', { name: 'Select Package' }).click();
    await page.getByRole('button', { name: 'Latitude Finance AU Standard' }).click();
    await page.getByRole('combobox').first().selectOption('EMPLOYMENT');
    await page.getByRole('textbox', { name: 'e.g. Latitude Finance' }).click();
    await page.getByRole('textbox', { name: 'e.g. Latitude Finance' }).fill('Latitude Finance');
    await page.getByRole('textbox', { name: 'Length must be below' }).click();
    await page.getByRole('textbox', { name: 'Length must be below' }).fill('qa');
    await page.getByRole('textbox', { name: 'e.g. Sydney' }).click();
    await page.getByRole('textbox', { name: 'e.g. Sydney' }).fill('Sydney');
    await page.getByRole('combobox').nth(1).selectOption('NSW');
    await page.getByRole('button', { name: 'Confirm' }).click();
    await page.getByRole('textbox', { name: 'Add Additional Check' }).click();
    await page.getByRole('textbox', { name: 'Add Additional Check' }).press('Escape');
    await page.locator('.jss422.jss458.jss475 > .jss588 > .jss604 > .jss612').first().click();
    await page.locator('.jss604.jss611.jss606 > .jss612').fill('12345678990');
    await page.locator('div:nth-child(10) > .jss588 > .jss604 > .jss612').click();
    await page.locator('.jss604.jss611.jss606 > .jss612').fill('1234567890');
    await page.getByRole('button', { name: 'Create' }).click();
    await expect(page.getByRole('textbox').first()).toBeVisible();
    await expect(page.getByRole('textbox').first()).toHaveValue('Test');
    await page.locator('input[type="email"]').click();
    await page.locator('div:nth-child(2) > .jss904').click();
    await expect(page.locator('input[type="email"]')).toHaveValue('test@test.com');
    await expect(page.getByRole('textbox').nth(2)).toHaveValue('1');
    await expect(page.getByRole('textbox').nth(3)).toHaveValue('1');
    await expect(page.getByRole('textbox').nth(4)).toHaveValue('qa');
    await expect(page.getByRole('link', { name: 'Company Latitude Finance' }).getByRole('textbox')).toHaveValue('Latitude Finance');
    await expect(page.getByRole('link', { name: 'Package Latitude Finance AU' }).locator('input[type="text"]')).toHaveValue('Latitude Finance AU Standard Employee Package');
    await expect(page.locator('div:nth-child(7) > a > .jss904 > .jss920 > .jss928')).toHaveValue('Yu Zhang');
    await expect(page.locator('.jss813.jss849.jss856.jss866 > .jss904 > .jss920 > .jss928').first()).toHaveValue('1234567890');
    await expect(page.locator('div:nth-child(9) > .jss904 > .jss920 > .jss928')).toHaveValue('12345678990');
    await expect(page.locator('div:nth-child(11) > .jss904 > .jss920 > .jss928')).toHaveValue('0ctx4i');
    await expect(page.locator('div:nth-child(12) > .jss904 > .jss920 > .jss928')).toHaveValue('5:21 AM on 17/02/2026');
    await expect(page.locator('#react-root')).toContainText('National Police Check');
    await expect(page.locator('#react-root')).toContainText('Academic');
    await expect(page.locator('#react-root')).toContainText('Entitlement To Work');
    await expect(page.locator('#react-root')).toContainText('Reference');
    await page.getByRole('button', { name: 'Authorize Order' }).click();
    await expect(page.getByText('National Police CheckNational Police CheckStatus VerifierPriceTime Target (')).toBeVisible();
    await expect(page.getByText('AcademicAcademicStatus')).toBeVisible();
    await expect(page.getByText('Entitlement To WorkEntitlement To WorkStatus VerifierPriceTime Target (hours)')).toBeVisible();
    await expect(page.getByText('ReferenceReferenceStatus')).toBeVisible();
    await page.getByRole('button', { name: 'Checks' }).click();
    await page.getByRole('textbox').first().fill('National Po');
    await page.goto('https://sandbox.gk.mvsi.com/checks');
    await page.getByRole('textbox').first().fill('National Police Check');
    await page.getByRole('checkbox', { name: '596 National Police Check' }).click();
    await expect(page.getByRole('textbox').first()).toHaveValue('Test');
    await expect(page.locator('input[type="email"]')).toHaveValue('test@test.com');
    await expect(page.getByRole('textbox', { name: '+' })).toHaveValue('+11');
    await expect(page.getByRole('textbox').nth(3)).toHaveValue('qa');
    await expect(page.getByRole('link', { name: 'Company Latitude Finance' }).getByRole('textbox')).toHaveValue('Latitude Finance');
    await expect(page.getByRole('textbox', { name: 'Verifier' })).toHaveValue('Jane Doe');
    await expect(page.getByRole('link', { name: 'Client Yu Zhang' }).locator('input[type="text"]')).toHaveValue('Yu Zhang');
    await expect(page.locator('input[type="currency"]')).toHaveValue('$0.00');
    await expect(page.getByRole('spinbutton').first()).toHaveValue('0');
    await expect(page.getByRole('spinbutton').nth(1)).toHaveValue('0');
    await page.getByRole('button', { name: 'Orders' }).click();
    await page.getByRole('checkbox', { name: '326 Test qa Latitude Finance' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.locator('button').nth(5).click();
    const page1 = await page1Promise;
    await page1.getByRole('button', { name: 'Next' }).click();
    await page1.locator('input[name="6613891377853545"]').click();
    await page1.locator('input[name="6613891377853545"]').fill('q');
    await page1.locator('input[name="9490280259906658"]').click();
    await page1.locator('input[name="9490280259906658"]').fill('a');
    await page1.locator('input[type="email"]').click();
    await page1.locator('input[type="email"]').fill('test@test.com');
    await page1.getByRole('textbox').nth(4).click();
    await page1.getByRole('textbox').nth(4).fill('11');
    await page1.getByRole('textbox', { name: 'DD', exact: true }).click();
    await page1.getByRole('textbox', { name: 'DD', exact: true }).fill('1');
    await page1.getByRole('textbox', { name: 'MM' }).click();
    await page1.getByRole('textbox', { name: 'MM' }).fill('1');
    await page1.getByRole('textbox', { name: 'YYYY' }).click();
    await page1.getByRole('textbox', { name: 'YYYY' }).fill('1999');
    await page1.locator('select[name="Gender"]').selectOption('M');
    await page1.getByRole('checkbox', { name: 'Please check if the address' }).check();
    await page1.getByRole('textbox', { name: 'L' }).click();
    await page1.getByRole('textbox', { name: 'L' }).fill('1');
    await page1.getByRole('textbox', { name: 'L' }).click();
    await page1.getByRole('textbox', { name: 'L' }).fill('11');
    await page1.locator('.jss140.jss170 > .jss447 > .jss483 > .jss491').first().click();
    await page1.getByRole('textbox', { name: 'U' }).click();
    await page1.getByRole('textbox', { name: 'U' }).fill('1');
    await page1.locator('.jss483.jss488 > .jss491').click();
    await page1.locator('.jss483.jss488 > .jss491').fill('1');
    await page1.locator('.jss140.jss170.jss180.jss193.jss206.jss218 > .jss447 > .jss483 > .jss491').first().click();
    await page1.locator('.jss483.jss490.jss485 > .jss491').fill('Sydney');
    await page1.locator('.jss483.jss490.jss485 > .jss491').press('Tab');
    await page1.locator('.jss483.jss490.jss485 > .jss491').fill('Street');
    await page1.locator('.jss483.jss490.jss485 > .jss491').press('Tab');
    await page1.locator('.jss483.jss490.jss485 > .jss491').fill('CBD');
    await page1.locator('.jss483.jss490.jss485 > .jss491').press('Tab');
    await page1.getByRole('textbox', { name: 'Postcode/Zipcode *' }).fill('2000');
    await page1.locator('select[name="State"]').selectOption('NSW');
    await page1.getByRole('button', { name: 'Next' }).click();
    await page1.getByRole('button', { name: 'Sign' }).click();
    await page1.getByRole('menuitem', { name: 'Type Signature' }).click();
    await page1.getByRole('textbox').click();
    await page1.getByRole('textbox').fill('qa');
    await page1.getByRole('button', { name: 'Save and Continue' }).click();
    await page1.getByRole('button', { name: 'Proceed' }).click();
    await page1.getByRole('button', { name: 'I don\'t own any of these' }).click();
    await page1.getByRole('button', { name: 'Okay' }).click();
    await page1.getByRole('button').nth(2).click();
    await page1.getByRole('option', { name: 'Australian Passport' }).click();
    await page1.locator('input[type="passport"]').click();
    await page1.locator('input[type="passport"]').fill('ra1111111');
    await page1.getByRole('button', { name: 'Take Picture' }).click();
    await page1.getByRole('button', { name: 'Take Photo' }).click();
    await page1.getByRole('button', { name: 'Verify Your Details' }).click();
    await page1.getByRole('button', { name: 'Ok' }).click();
    await page1.getByRole('button', { name: 'Verify Your Details' }).click();
    await page1.getByRole('button', { name: 'Ok' }).click();
    await page1.getByRole('button', { name: 'Verify Your Details' }).click();
    await page1.getByRole('button', { name: 'Ok' }).click();
    await page1.getByRole('button').nth(2).click();
    await page1.getByRole('option', { name: 'Foreign Passport' }).click();
    await page1.locator('input[type="foreignPassport"]').click();
    await page1.locator('input[type="foreignPassport"]').fill('1');
    await page1.getByRole('combobox').selectOption('AFG');
    await page1.getByRole('button', { name: 'Take Picture' }).click();
    await page1.getByRole('button', { name: 'Take Photo' }).click();
    await page1.getByRole('button', { name: 'Verify Your Details' }).click();
    await page1.getByRole('button').nth(3).click();
    await page1.getByRole('option', { name: 'Bank Card' }).click();
    await page1.getByRole('button', { name: 'Take Picture' }).click();
    await page1.getByText('CancelTake Photo').click();
    await page1.getByRole('button', { name: 'Take Photo' }).click();
    await page1.getByRole('button', { name: 'Verify Your Details' }).click();
    await page1.getByRole('button').nth(3).click();
    await page1.getByRole('option', { name: 'Credit Card' }).click();
    await page1.getByRole('button', { name: 'Take Picture' }).click();
    await page1.getByRole('button', { name: 'Take Photo' }).click();
    await page1.getByRole('button', { name: 'Verify Your Details' }).click();
    await page1.getByRole('button', { name: 'Take Picture' }).click();
    await page1.getByRole('button', { name: 'Okay' }).click();
    await page1.getByRole('button', { name: 'Take Photo' }).click();
    await page1.getByRole('button', { name: 'Verify Your Details' }).click();
    await page1.getByRole('button', { name: 'Continue to Additional Info' }).click();
    await page1.getByRole('combobox').selectOption('AUS');
    await page1.locator('select[name="Birth State"]').selectOption('NSW');
    await page1.locator('form').filter({ hasText: 'National Police CheckFirst up' }).locator('input[type="text"]').click();
    await page1.locator('form').filter({ hasText: 'National Police CheckFirst up' }).locator('input[type="text"]').fill('town');
    await page1.getByRole('textbox', { name: 'DD' }).click();
    await page1.getByRole('textbox', { name: 'DD' }).fill('1');
    await page1.getByRole('textbox', { name: 'MM' }).click();
    await page1.getByRole('textbox', { name: 'MM' }).fill('1');
    await page1.getByRole('textbox', { name: 'YYYY' }).click();
    await page1.getByRole('textbox', { name: 'YYYY' }).fill('1999');
    await page1.locator('form').filter({ hasText: 'National Police CheckFirst up' }).getByRole('button').click();
    await page1.getByRole('textbox').nth(4).fill('name');
    await page1.getByRole('textbox').nth(4).press('Tab');
    await page1.getByRole('textbox').nth(5).fill('qualification');
    await page1.getByRole('textbox').nth(5).press('Tab');
    await page1.locator('input[type="text"]').nth(3).fill('TAFE');
    await page1.locator('input[type="text"]').nth(3).press('Tab');
    await page1.locator('input[type="text"]').nth(4).fill('TAFE');
    await page1.locator('input[type="text"]').nth(4).press('Tab');
    await page1.getByRole('textbox', { name: 'Graduation Date *' }).fill('1/1/1999');
    await page1.locator('form').filter({ hasText: 'AcademicYour Name (Name' }).getByRole('button').click();
    await page1.locator('.jss1723.jss1728 > .jss1731').fill('1');
    await page1.getByRole('button').nth(5).click();
    await page1.getByRole('button').nth(5).click();
    await page1.getByRole('button').nth(4).click();
    await page1.getByRole('button').nth(4).click();
    await page1.getByRole('option', { name: 'Afghanistan' }).click();
    await page1.locator('form').filter({ hasText: 'Entitlement To WorkName on' }).locator('button').click();
    await page1.getByRole('button', { name: 'Confirm' }).click();
    await page1.locator('.jss1723.jss1728 > .jss1731').fill('name');
    await page1.locator('input[type="email"]').click();
    await page1.locator('input[type="email"]').fill('email@email.com');
    await page1.locator('input[type="email"]').press('Tab');
    await page1.getByRole('textbox', { name: 'Where you worked for referee' }).fill('company');
    await page1.getByRole('textbox', { name: 'Where you worked for referee' }).press('Tab');
    await page1.locator('.jss1723.jss1730.jss1725 > .jss1731').fill('1');
    await page1.locator('.jss1723.jss1730.jss1725 > .jss1731').press('Tab');
    await page1.locator('.jss1723.jss1730.jss1725 > .jss1731').fill('colleague');
    await page1.locator('.jss1723.jss1730.jss1725 > .jss1731').press('Tab');
    await page1.getByRole('textbox', { name: 'From Date *' }).fill('1/1/1990');
    await page1.getByRole('textbox', { name: 'To Date *' }).click();
    await page1.getByRole('textbox', { name: 'To Date *' }).fill('1/1/1999');
    await page1.locator('form').filter({ hasText: 'ReferenceReferee Name *' }).locator('button').click();
    await page1.getByRole('button', { name: 'Save and Continue' }).click();
    await page1.locator('button').filter({ hasText: /^Logout$/ }).click();
    await page.getByRole('button', { name: 'Checks' }).click();
    await page.getByRole('textbox').first().click();
    await page.getByRole('textbox').first().fill('national police chec');
    await page.goto('https://sandbox.gk.mvsi.com/checks');
    await page.getByRole('textbox').first().fill('national police check');
    await page.getByRole('checkbox', { name: '596 National Police Check' }).click();
    await expect(page.getByRole('textbox').first()).toHaveValue('Test');
    await expect(page.locator('input[type="email"]')).toHaveValue('test@test.com');
    await expect(page.getByRole('textbox', { name: '+' })).toHaveValue('+11');
    await expect(page.getByRole('textbox').nth(3)).toHaveValue('qa');
    await expect(page.getByRole('link', { name: 'Company Latitude Finance' }).getByRole('textbox')).toHaveValue('Latitude Finance');
    await expect(page.getByRole('textbox', { name: 'Verifier' })).toHaveValue('Jane Doe');
    await expect(page.getByRole('link', { name: 'Client Yu Zhang' }).locator('input[type="text"]')).toHaveValue('Yu Zhang');
    await expect(page.locator('input[type="currency"]')).toHaveValue('$0.00');
    await expect(page.locator('.jss2052.jss2088.jss2106 > .jss2143 > .jss2159 > .jss2167').first()).toHaveValue('q');
    await expect(page.locator('.jss2051.jss2074 > div:nth-child(3) > .jss2143 > .jss2159 > .jss2167')).toHaveValue('a');
    await expect(page.locator('.jss2051.jss2074 > div:nth-child(4) > .jss2143 > .jss2159 > .jss2167')).toHaveValue('test@test.com');
    await expect(page.locator('div:nth-child(5) > .jss2143 > .jss2159 > .jss2167')).toHaveValue('11');
    await expect(page.locator('.jss2052.jss2088.jss2114 > .jss2143 > .jss2159 > .jss2167')).toHaveValue('L 11 1/1 Sydney Street, CBD, NSW, 2000, Australia (AUS)');
    await page.getByRole('button', { name: 'OPEN' }).click();
    await page.getByRole('option', { name: 'NDCO' }).click();
    await page.getByRole('checkbox', { name: 'I have confirmed the above' }).check();
    await page.getByRole('button', { name: 'Send ACIC Request' }).click();
    await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
    await page.getByRole('combobox').nth(1).selectOption('EMPLOYMENT');
    await page.locator('.jss2052.jss2088.jss2131 > .jss2143 > .jss2159 > .jss2167').first().click();
    await page.locator('.jss2159.jss2166.jss2161 > .jss2167').fill('qa');
    await page.locator('.jss2052 > .jss2051 > div:nth-child(3) > .jss2143 > .jss2159 > .jss2167').first().click();
    await page.locator('.jss2159.jss2166.jss2161 > .jss2167').fill('nsw');
    await page.locator('.jss2052 > .jss2051 > div:nth-child(4) > .jss2143 > .jss2159 > .jss2167').click();
    await page.locator('.jss2159.jss2166.jss2161 > .jss2167').fill('nsw');
    await page.getByRole('combobox').nth(2).selectOption('NSW');
    await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
    await page.getByRole('button', { name: 'Send ACIC Request' }).click();
});