import { test, expect } from '@playwright/test';

test.describe.serial('GateKeeper Tests', () => {
    test.beforeEach('test', async ({ page }) => {
        await page.goto('https://sandbox.gk.mvsi.com/');
        await page.getByRole('textbox', { name: 'Email Address' }).click();
        await page.getByRole('textbox', { name: 'Email Address' }).fill('yuz@mvsi.com');
        await page.getByRole('textbox', { name: 'Email Address' }).press('Tab');
        await page.getByRole('textbox', { name: 'Password' }).fill('Test.1234');
        await page.getByRole('button', { name: 'Login' }).click();
        await page.getByRole('button', { name: 'Orders' }).click();
        await page.locator('button').nth(2).click();
        await page.getByRole('textbox').first().fill('CandidateName');
        await page.locator('input[type="email"]').click();
        await page.locator('input[type="email"]').fill('candidate@email.com');
        await page.getByRole('textbox').nth(2).click();
        await page.getByRole('textbox').nth(2).fill('61');
        await page.getByRole('textbox').nth(3).click();
        await page.getByRole('textbox').nth(3).fill('1234');
        await page.getByRole('textbox').nth(4).click();
        await page.getByRole('textbox').nth(4).fill('candidateRole');
        await page.getByRole('textbox', { name: 'Select Company *' }).click();
        await page.getByRole('textbox', { name: 'Select Company *' }).fill('Latitude Finance');
        await page.getByRole('button', { name: 'Latitude Finance' }).click();
        await page.getByRole('textbox', { name: 'Select Client *' }).click();
        await page.getByRole('textbox', { name: 'Select Client *' }).fill('Yu Zhang');
        await page.getByRole('button', { name: 'Yu Zhang', exact: true }).click();
        await page.getByRole('textbox', { name: 'Select Package' }).click();
        await page.getByRole('button', { name: 'Latitude Finance AU Standard' }).click();
        await page.getByRole('combobox').first().selectOption('EMPLOYMENT');
        await page.getByRole('textbox', { name: 'e.g. Latitude Finance' }).click();
        await page.getByRole('textbox', { name: 'e.g. Latitude Finance' }).fill('Latitude Finance');
        await page.getByRole('textbox', { name: 'Length must be below' }).click();
        await page.getByRole('textbox', { name: 'Length must be below' }).fill('candidateRole');
        await page.getByRole('textbox', { name: 'e.g. Sydney' }).click();
        await page.getByRole('textbox', { name: 'e.g. Sydney' }).fill('Sydney');
        await page.getByRole('combobox').nth(1).selectOption('NSW');
        await page.waitForTimeout(500);
        await page.getByRole('button', { name: 'Confirm' }).click();
        const orderRefInput = await page.locator('label').filter({ hasText: /Order.*Ref.*Number/ })
            .locator('..')
            .locator('input[type="text"]');
        await orderRefInput.click();
        await orderRefInput.fill('12345');
        await page.getByRole('button', { name: 'Create' }).click();
        await expect(page.getByRole('textbox').first()).toHaveValue('CandidateName');
        await expect(page.locator('input[type="email"]')).toHaveValue('candidate@email.com');
        await expect(page.getByRole('textbox').nth(2)).toHaveValue('61');
        await expect(page.getByRole('textbox').nth(3)).toHaveValue('1234');
        await expect(page.getByRole('textbox').nth(4)).toHaveValue('candidateRole');
        await expect(page.getByRole('link', { name: 'Company Latitude Finance' }).getByRole('textbox')).toHaveValue('Latitude Finance');
        await expect(page.getByRole('link', { name: 'Package Latitude Finance AU' }).locator('input[type="text"]')).toHaveValue('Latitude Finance AU Standard Employee Package');
        await expect(page.getByRole('cell', { name: 'National Police Check' })).toBeVisible();
        await expect(page.getByRole('cell', { name: 'Academic' })).toBeVisible();
        await expect(page.getByRole('cell', { name: 'Entitlement To Work' })).toBeVisible();
        await expect(page.getByRole('cell', { name: 'Reference' })).toBeVisible();
        await page.getByRole('button', { name: 'Authorize Order' }).click();
        await expect(page.getByText('National Police CheckNational Police CheckStatus VerifierPriceTime Target (')).toBeVisible();
        await expect(page.getByText('AcademicAcademicStatus')).toBeVisible();
        await expect(page.getByText('Entitlement To WorkEntitlement To WorkStatus VerifierPriceTime Target (hours)')).toBeVisible();
        await expect(page.getByText('ReferenceReferenceStatus')).toBeVisible();
    });

    test('Fill in candidate info', async ({ page }) => {
        const page2Promise = page.waitForEvent('popup');
        await page.locator('button').nth(5).click();
        const page2 = await page2Promise;
        await page2.getByRole('button', { name: 'Next' }).click();
        await page2.locator('div:has(> label:text("First Name")) input').fill('firstName');
        await page2.locator('div:has(> label:text("Last Name")) input').fill('lastName');
        await page2.locator('input[type="email"]').click();
        await page2.locator('input[type="email"]').fill('test@gmail.com');
        await page2.locator('input[type="email"]').press('Tab');
        await page2.getByRole('textbox').nth(4).fill('1');
        await page2.getByRole('textbox', { name: 'DD', exact: true }).click();
        await page2.getByRole('textbox', { name: 'DD', exact: true }).fill('1');
        await page2.getByRole('textbox', { name: 'MM' }).click();
        await page2.getByRole('textbox', { name: 'MM' }).fill('1');
        await page2.getByRole('textbox', { name: 'YYYY' }).click();
        await page2.getByRole('textbox', { name: 'YYYY' }).fill('1999');
        await page2.locator('select[name="Gender"]').selectOption('M');
        await page2.getByRole('checkbox', { name: 'Please check if the address' }).check();
        await page2.locator('div:has(> label:text("Street Number")) input').fill('1');
        await page2.locator('div:has(> label:text("Street Name")) input').fill('streetName');
        await page2.locator('div:has(> label:text("Suburb")) input').fill('suburb');
        await page2.locator('div:has(> label:text("Postcode/Zipcode *")) input').fill('2000');
        await page2.locator('select[name="State"]').selectOption('NSW');
        await page2.getByRole('button', { name: 'Next' }).click();
        await page2.getByRole('button', { name: 'Sign' }).click();
        await page2.getByRole('menuitem', { name: 'Type Signature' }).click();
        await page2.getByRole('textbox').click();
        await page2.getByRole('textbox').fill('fl');
        await page2.getByRole('button', { name: 'Save and Continue' }).click();
        await page2.getByRole('button', { name: 'Proceed' }).click();
        await page2.locator('label[for="Choose your document Type"] + div div[role="button"]').click();
        await page2.getByRole('option', { name: 'Australian Birth Certificate' }).click();
        const birthFileChooserPromise = page2.waitForEvent('filechooser');
        await page2.getByLabel('Upload Image').click();
        const birthFileChooser = await birthFileChooserPromise;
        await birthFileChooser.setFiles('tests/resources/Sample_Birth_Certificate.jpg');
        await page2.locator('button[type="submit"]', { hasText: 'Verify Your Details' }).click();
        await page2.waitForTimeout(2000);
        await page2.locator('label[for="Choose your document Type"] + div div[role="button"]').click();
        await page2.getByRole('option', { name: 'Australian Marriage Certificate' }).click();
        const marriageFileChooserPromise = page2.waitForEvent('filechooser');
        await page2.getByLabel('Upload Image').click();
        const marriageFileChooser = await marriageFileChooserPromise;
        await marriageFileChooser.setFiles('tests/resources/Sample_Marriage_Certificate.jpg');
        await page2.locator('button[type="submit"]', { hasText: 'Verify Your Details' }).click();
        await page2.waitForTimeout(2000);
        await page2.locator('label[for="Choose your document Type"] + div div[role="button"]').click();
        await page2.getByRole('option', { name: 'Bank Card' }).click();
        const bankcardChooserPromise = page2.waitForEvent('filechooser');
        await page2.getByLabel('Upload Image').click();
        const bankcardChooser = await bankcardChooserPromise;
        await bankcardChooser.setFiles('tests/resources/Sample_Bank_Card.jpg');
        await page2.locator('button[type="submit"]', { hasText: 'Verify Your Details' }).click();
        await page2.waitForTimeout(2000);
        await page2.locator('label[for="Choose your document Type"] + div div[role="button"]').click();
        await page2.getByRole('option', { name: 'Credit Card' }).click();
        const creditCardChooserPromise = page2.waitForEvent('filechooser');
        await page2.getByLabel('Upload Image').click();
        const creditCardChooser = await creditCardChooserPromise;
        await creditCardChooser.setFiles('tests/resources/Sample_Credit_Card.jpg');
        await page2.locator('button[type="submit"]', { hasText: 'Verify Your Details' }).click();
        await page2.waitForTimeout(2000);
        await page2.getByRole('button', { name: 'Take Picture' }).click();
        await page2.getByRole('button', { name: 'Okay' }).click();
        await page2.getByRole('button', { name: 'Take Photo' }).click();
        await page2.locator('button[type="submit"]', { hasText: 'Verify Your Details' }).click();
        await page2.waitForTimeout(5000);
    });

    test('National Police Check', async ({ page }) => {
        await page.waitForTimeout(1000);
        await page.getByRole('button', { name: 'Checks' }).click();
        await page.getByRole('textbox').first().click();
        await page.getByRole('textbox').first().fill('national police check');
        await page.waitForTimeout(2000);
        await page.getByRole('cell', { name: 'National Police Check' }).first().click();
        await page.waitForTimeout(2000);
    });
});
